version: '3.5'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/vhost/:/etc/nginx/vhost.d:ro
      - ./nginx/conf.d/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
      - ./static/:/code/static
      - ./media/:/code/media

  postgres:
    container_name:  postgres-db
    image:           postgres:9.6.6
    restart: "always"
    ports:
      - 5432:5432 # Bind host port 5432 to PostgreSQL port 5432
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    env_file: .env
    environment:
      - LC_ALL=C.UTF-8


  redis:
    container_name: redis
    image: redis:rc-buster
    ports:
      - "6379:6379"
    restart: on-failure
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: celery.dockerfile
    env_file:
      - .env
    volumes:
      - .:/code
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis

  web:
    container_name: pragmadev
    build: .
    restart: "always"
    env_file: .env
    environment:
      - VIRTUAL_HOST=34.89.179.178,127.0.0.1
      - VIRTUAL_PORT=8000
      - TIMEOUT=300
      - HTTP_PORT=8000
      - STATS_PORT=8001
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - postgres
    depends_on:
      - "postgres"
networks:
  default:
    external:
      name: nginx-proxy
