# Generated by Django 2.2.12 on 2020-04-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0002_auto_20200415_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='from_email',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_html',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_text',
        ),
        migrations.RemoveField(
            model_name='email',
            name='template_key',
        ),
        migrations.RemoveField(
            model_name='email',
            name='to_email',
        ),
        migrations.AddField(
            model_name='email',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
