# Generated by Django 2.2.12 on 2020-04-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0004_auto_20200415_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='bool',
            field=models.BooleanField(default=False),
        ),
    ]
