# Generated by Django 2.2.12 on 2020-04-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0006_auto_20200415_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendemail',
            name='bool',
        ),
        migrations.RemoveField(
            model_name='sendemail',
            name='plain_text',
        ),
    ]
